@include('components.modules.chat.modals.settings')
@include('components.modules.chat.modals.mic')
@include('components.modules.chat.modals.headphones')
@include('components.modules.chat.modals.explore')
@include('components.modules.chat.modals.downloads')
@include('components.modules.chat.modals.create-group', ['contacts' => $contacts ?? collect()])
@include('components.modules.chat.modals.new-dm', ['contacts' => $contacts ?? collect()])
@include('components.modules.chat.modals.create-personal-tag')
@include('components.modules.chat.modals.todo', ['todos' => $todos ?? collect()])
@include('components.modules.chat.modals.reactions')
@include('components.modules.chat.modals.forward', ['conversations' => $groups ?? collect()])
@include('components.modules.chat.modals.report')
@include('components.modules.chat.modals.gif-stickers')
@include('components.modules.chat.modals.call')
@include('components.modules.chat.modals.pinned-messages')
@include('components.modules.chat.modals.notifications-settings')
@include('components.modules.chat.modals.search-messages')
@include('components.modules.chat.modals.members')
@include('components.modules.chat.modals.group-settings')
@include('components.modules.chat.modals.block-user')
@include('components.modules.chat.modals.create-channel')
@include('components.modules.chat.modals.join-requests')
@if(auth()->user()->isModerator())
    @include('components.modules.chat.modals.manage-members')
    @include('components.modules.chat.modals.add-member-quick')
@endif
@include('components.modules.chat.modals.all-servers')
@include('components.modules.chat.modals.video-preview')
@include('components.modules.chat.modals.confirm')
@include('components.modules.chat.modals.mute-user')
@include('components.modules.chat.modals.spin-wheel')
@include('components.modules.chat.modals.duck-race')
